[modules]
ng = 'nmrglue'
np = 'numpy'
plt = 'matplotlib.pyplot'
tins = 'tins'
qutip = 'qutip'
sym = 'sympy'


[functions]
print = 'rich'
sqrt = 'numpy'
pi = 'numpy'
sin = 'numpy'
cos = 'numpy'
tan = 'numpy'
log = 'numpy'
log10 = 'numpy'
linspace = 'numpy'
arange = 'numpy'
symbols = 'sympy'
expm = 'scipy.linalg'
curve_fit = 'scipy.optimize'



[constants]
x = 'np.linspace(-10, 10, 100)'
ln = 'np.log'
kb =  '1.38064852e-23'
R = '8.314'
h = '6.62607015e-34'
hbar = '1.054571817e-34'
'Ï€' = 'np.pi'
