[modules]
ng = 'nmrglue'
np = 'numpy'
plt = 'matplotlib.pyplot'
tins = 'tins'
qutip = 'qutip'
sym = 'sympy'
fft = 'numpy.fft'
random = 'numpy.random'
umath = 'uncertainties.umath'
pint = 'pint'

[functions]
print = 'rich'
sqrt = 'numpy'
pi = 'numpy'
sin = 'numpy'
cos = 'numpy'
tan = 'numpy'
log = 'numpy'
log10 = 'numpy'
linspace = 'numpy'
arange = 'numpy'
random = 'numpy'
expm = 'scipy.linalg'
curve_fit = 'scipy.optimize'
plot = 'matplotlib.pyplot'
show = 'matplotlib.pyplot'
hist = 'matplotlib.pyplot'
scatter = 'matplotlib.pyplot'
imshow = 'matplotlib.pyplot'
symbols = 'sympy'
ufloat = 'uncertainties'