#!/bin/bash

PYCALC=$HOME/data/repositories/ipycalc
IPY=$HOME/miniconda/envs/ipycalc/bin/ipython


kitty-terminal --single-instance \
    --config $PYCALC/pycalc_kitty.conf \
    -d $PYCALC \
    $IPY -i --no-confirm-exit --no-banner -c  \
    "exec(open(\"python_thread_import.py\").read(), globals())"