#!/bin/bash

PYCALC=$HOME/data/repositories/pycalc
IPY=$HOME/miniconda/envs/pycalc/bin/ipython


/opt/kitty/0.22.2/bin/kitty --single-instance \
    --config $PYCALC/pycalc_kitty.conf \
    -d $PYCALC \
    $IPY -i --no-confirm-exit --no-banner -c  \
    "exec(open(\"python_thread_import.py\").read(), globals())"

