#!/bin/bash

IPYCALC_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
IPYCALC=$IPYCALC/ipycalc
IPY=$HOME/miniconda/envs/ipycalc/bin/ipython
KITTY=$IPYCALC_DIR/kitty.app/bin/kitty


$KITTY --single-instance \
      --config $IPYCALC/src/defaults/ipycalc_kitty.conf \
      -d $IPYCALC/src \
      $IPY -i --no-confirm-exit --no-banner -c  \
      "exec(open(\"python_thread_import.py\").read(), globals())"
